// Package beta - designer.go provides the interactive Beta Designer.
//
// The Designer runs a 6-phase interview to create the visual language
// for a project. All design tokens — palettes, effects, animations,
// style rules — are generated by Beta from the conversation.
//
// Phases:
//  1. Design Vision — aesthetic, mood, audience, accessibility
//  2. Import & Study — existing brand assets, Figma files, sketches
//  3. Color & Typography — palette options, type scale
//  4. Motion & Feel — animations, transitions, micro-interactions
//  5. Effects & Polish — glassmorphism, gradients, shadows, particles
//  6. Rules & Export — bounds, constraints, Figma export
//
// Beta reads Alpha's rulebook for contextual questions when provided.
// Alpha and Beta communicate via the Collaboration API — if a user gives
// design ideas to Alpha, they're forwarded to Beta, and vice versa.
package beta

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/partir/core/internal/interview"
	"github.com/partir/core/pkg/plugin"
)

// Designer orchestrates the interactive design interview.
type Designer struct {
	engine       *interview.Engine
	workspace    *Workspace
	intake       *interview.IntakeProcessor
	project      string
	alphaRef     string       // optional Alpha rulebook reference for contextual questions
	designPlugin DesignPlugin // optional design tool plugin (Figma, Sketch, etc.)
}

// DesignerConfig holds configuration for creating a new Designer.
type DesignerConfig struct {
	Workspace    *Workspace
	Executor     plugin.Executor
	Assembly     *interview.PairAssembly
	GraphName    string
	Graph        interview.GraphClient
	Ledger       interview.LedgerAppender
	AlphaRef     string       // e.g., "my_game@0.1.0"
	DesignPlugin DesignPlugin // optional (nil if no design tool configured)
}

// NewDesigner creates a new Beta Designer.
func NewDesigner(project string, cfg DesignerConfig) *Designer {
	projectDir := filepath.Join(cfg.Workspace.BaseDir, project)

	engine := interview.New(interview.Config{
		Executor:   cfg.Executor,
		Assembly:   cfg.Assembly,
		ActivePair: cfg.Assembly.ActiveBeta(),
		GraphName:  cfg.GraphName,
		Graph:      cfg.Graph,
		Ledger:     cfg.Ledger,
		ProjectDir: projectDir,
	})

	return &Designer{
		engine:       engine,
		workspace:    cfg.Workspace,
		intake:       interview.NewIntakeProcessor(cfg.Executor),
		project:      project,
		alphaRef:     cfg.AlphaRef,
		designPlugin: cfg.DesignPlugin,
	}
}

// Start runs the full interactive design session.
func (d *Designer) Start(ctx context.Context) (*Rulebook, error) {
	fmt.Println("╔════════════════════════════════════════════════════════╗")
	fmt.Println("║          BETA — Design Architect                      ║")
	fmt.Printf("║          Project: %-36s ║\n", d.project)
	fmt.Println("╚════════════════════════════════════════════════════════╝")
	fmt.Println()
	fmt.Println("  I'm Beta. I'll help you define the look, feel, and")
	fmt.Println("  interaction design of your project.")
	fmt.Println()

	if d.alphaRef != "" {
		fmt.Printf("  📐 Reading architecture from: %s\n", d.alphaRef)
		fmt.Println("     I'll ask contextual design questions based on your data models.")
		fmt.Println()
	}

	fmt.Println("  Commands: /done (next phase), /quit (exit), /history, /decisions")
	fmt.Println()

	// Initialize workspace if it doesn't exist
	if !d.workspace.Exists(d.project) {
		if _, err := d.workspace.Init(d.project); err != nil {
			return nil, fmt.Errorf("init workspace: %w", err)
		}
	}

	// Run all phases
	phases := interview.BetaPhases()
	for _, phase := range phases {
		result, err := d.engine.RunPhase(ctx, phase)
		if err != nil {
			return nil, fmt.Errorf("phase %s failed: %w", phase.ID, err)
		}

		if result != nil && len(result.Extracted) > 0 {
			log.Printf("[beta] Phase %s produced %d artifacts", phase.ID, len(result.Extracted))
		}
	}

	// Offer Figma export if plugin is configured
	if d.designPlugin != nil {
		d.offerDesignExport(ctx)
	}

	// Load the generated workspace
	rb, err := d.workspace.Load(d.project)
	if err != nil {
		log.Printf("[beta] Warning: could not load final rulebook: %v", err)
		return NewRulebook(d.project), nil
	}

	fmt.Println()
	fmt.Println("━━━ Design Language Complete ━━━")
	fmt.Printf("  Design: %s\n", d.project)
	fmt.Printf("  Palettes:   %d\n", len(rb.RenderVocab.Palettes))
	fmt.Printf("  Effects:    %d\n", len(rb.RenderVocab.Effects))
	fmt.Printf("  Animations: %d\n", len(rb.RenderVocab.Animations))
	fmt.Println()

	return rb, nil
}

// StartWithUpload runs the session with an initial file upload.
func (d *Designer) StartWithUpload(ctx context.Context, uploadPath string) (*Rulebook, error) {
	result, err := d.intake.ProcessFile(ctx, uploadPath)
	if err != nil {
		return nil, fmt.Errorf("process upload %s: %w", uploadPath, err)
	}

	fmt.Printf("📄 Processed: %s (%s)\n", filepath.Base(uploadPath), result.FileType)
	fmt.Printf("   Summary: %s\n\n", result.Summary)

	// Save intake result
	intakePath := filepath.Join(d.workspace.BaseDir, d.project, "intake_"+filepath.Base(uploadPath)+".json")
	if err := writeDesignJSON(intakePath, result); err != nil {
		log.Printf("[beta] Warning: could not save intake result: %v", err)
	}

	return d.Start(ctx)
}

// Resume re-enters a previous session using graph memory.
func (d *Designer) Resume(ctx context.Context) (*Rulebook, error) {
	fmt.Println("╔════════════════════════════════════════════════════════╗")
	fmt.Println("║          BETA — Resuming Design Session               ║")
	fmt.Printf("║          Project: %-36s ║\n", d.project)
	fmt.Println("╚════════════════════════════════════════════════════════╝")
	fmt.Println()

	if err := d.engine.Resume(ctx); err != nil {
		return nil, fmt.Errorf("resume session: %w", err)
	}

	return d.Start(ctx)
}

// ExportDesign exports the current rulebook to the configured design tool.
func (d *Designer) ExportDesign(ctx context.Context) (string, error) {
	if d.designPlugin == nil {
		return "", fmt.Errorf("no design plugin configured")
	}

	rb, err := d.workspace.Load(d.project)
	if err != nil {
		return "", fmt.Errorf("load rulebook: %w", err)
	}

	ref, err := d.designPlugin.Export(ctx, rb)
	if err != nil {
		return "", fmt.Errorf("export to %s: %w", d.designPlugin.ID(), err)
	}

	fmt.Printf("✅ Exported to %s: %s\n", d.designPlugin.ID(), ref)
	return ref, nil
}

// ImportDesign imports design tokens from the configured design tool.
func (d *Designer) ImportDesign(ctx context.Context, ref string) error {
	if d.designPlugin == nil {
		return fmt.Errorf("no design plugin configured")
	}

	vocab, err := d.designPlugin.Import(ctx, ref)
	if err != nil {
		return fmt.Errorf("import from %s: %w", d.designPlugin.ID(), err)
	}

	// Write imported vocab to workspace
	vocabPath := filepath.Join(d.workspace.BaseDir, d.project, "render_vocab.json")
	data, _ := json.MarshalIndent(vocab, "", "  ")
	if err := os.WriteFile(vocabPath, data, 0644); err != nil {
		return fmt.Errorf("write render vocab: %w", err)
	}

	fmt.Printf("✅ Imported from %s: %d palettes, %d effects, %d animations\n",
		d.designPlugin.ID(),
		len(vocab.Palettes), len(vocab.Effects), len(vocab.Animations))

	return nil
}

// SyncDesign syncs changes from the design tool back to the rulebook.
func (d *Designer) SyncDesign(ctx context.Context, ref string) error {
	if d.designPlugin == nil {
		return fmt.Errorf("no design plugin configured")
	}

	rb, err := d.workspace.Load(d.project)
	if err != nil {
		return fmt.Errorf("load rulebook: %w", err)
	}

	diff, err := d.designPlugin.Sync(ctx, ref, rb)
	if err != nil {
		return fmt.Errorf("sync from %s: %w", d.designPlugin.ID(), err)
	}

	if diff.Summary != "" {
		fmt.Printf("📋 Changes from %s:\n   %s\n", d.designPlugin.ID(), diff.Summary)
	}

	fmt.Println("✅ Sync complete.")
	return nil
}

// offerDesignExport asks the user if they want to export to the design tool.
func (d *Designer) offerDesignExport(ctx context.Context) {
	fmt.Printf("\n🎨 Design plugin available: %s\n", d.designPlugin.ID())
	fmt.Println("   Would you like to export for visual review? (y/n)")
	// In a real implementation this would wait for user input
	// For now, just log the offer
	log.Printf("[beta] Design export offered via %s plugin", d.designPlugin.ID())
}

// writeDesignJSON writes data as indented JSON to a file.
func writeDesignJSON(path string, data interface{}) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	return enc.Encode(data)
}
